name:                newtype
version:             0.1.0.0
github:              "githubuser/newtype"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

dependencies:
- base >= 4.7 && < 5
- saltine
- base64-bytestring
- aeson
- text

executables:
  newtype:
    main:                Main.hs
    source-dirs:         .
